GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/1

###
DELETE http://localhost:3001/api/notes/1

###
POST http://localhost:3001/api/notes
content-type: application/json

{
  "content": "new note content",
  "important": false
}
